Add more context to the README
phylum-dev/birdcage pull request #29
Opened 2023-05-02 22:03 UTC by kylewillmon

Update some language and add details about the history of Birdcage and the technologies that are used.

2023-05-02 22:08 UTC, cd-work commented on README.md
>  ## Usage
I've already changed the examples in my stab at it. I'd say it is an improvement but feel free to tweak or discard:

## Example

An example for using Birdcage's API can be found in `./examples/sandbox`, which
runs an application with CLI-configurable restrictions applied.

Trying to run without an exceptions will produce an error:

```bash
$ cargo run --example sandbox -- echo "Hello, Sandbox\!"
Error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
```

Running the same command with explicit permissions allows execution:

```bash
$ cargo run --example sandbox -- -e /usr/bin/echo -e /usr/lib echo "Hello, Sandbox\!"
Hello, Sandbox!
```

Check out `cargo run --example sandbox -- --help` for more information on how to
use the example.
```

2023-05-02 22:08 UTC, louislang requested changes

2023-05-02 22:08 UTC, louislang commented on README.md
> +Birdcage was originally developed for use the [Phylum CLI] as an extra layer of
```suggestion
Birdcage was originally developed for use by the [Phylum CLI] as an extra layer of
```

2023-05-03 15:01 UTC, maxrake reviewed
Some initial suggestions (review ongoing):

* The Phylum website already [talks about Birdcage](https://www.phylum.io/defend-developers)
  * There is a logo used there that could/should also be used here
  * A link to <https://www.phylum.io/defend-developers> could be included here somewhere
* Complete the last two items on the [Community Standards](https://github.com/phylum-dev/birdcage/community) "checklist"
  * Contributing guide
  * Issue templates

Some badges might help to make things look "shinier." Here is the rendered form:

[![GitHub](https://img.shields.io/github/license/phylum-dev/birdcage)][license]
[![GitHub issues](https://img.shields.io/github/issues/phylum-dev/birdcage)][issues]
[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)][CoC]
[![Discord](https://img.shields.io/discord/1070071012353376387?logo=discord)][discord_invite]

[license]: https://github.com/phylum-dev/birdcage/blob/main/LICENSE
[issues]: https://github.com/phylum-dev/birdcage/issues
[CoC]: https://github.com/phylum-dev/birdcage/blob/main/CODE_OF_CONDUCT.md
[discord_invite]: https://discord.gg/Fe6pr5eW6p

And here is a copy/paste form:

```
[![GitHub](https://img.shields.io/github/license/phylum-dev/birdcage)][license]
[![GitHub issues](https://img.shields.io/github/issues/phylum-dev/birdcage)][issues]
[![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg)][CoC]
[![Discord](https://img.shields.io/discord/1070071012353376387?logo=discord)][discord_invite]

[license]: https://github.com/phylum-dev/birdcage/blob/main/LICENSE
[issues]: https://github.com/phylum-dev/birdcage/issues
[CoC]: https://github.com/phylum-dev/birdcage/blob/main/CODE_OF_CONDUCT.md
[discord_invite]: https://discord.gg/Fe6pr5eW6p
```

2023-05-03 15:04 UTC, cd-work commented
> There is a logo used there that could/should also be used here

First time I saw this logo now and it's amazing. Should definitely go in the repo too.

2023-05-03 21:20 UTC, kylewillmon commented on assets/Birdcage.png
This is 50% scale from the original because it looks better in the README

I could have scaled it by using an `<img />` tag with `height` or `width`, but then I would have to use an absolute path to the image. It seemed simpler to scale the image manually so that I can just use the markdown `![]()` syntax with a relative path.

2023-05-03 23:17 UTC, maxrake requested changes
One typo and a few suggestions.

2023-05-03 23:17 UTC, maxrake commented on README.md
> +![Birdcage logo](./assets/Birdcage.png)
```suggestion
[![Birdcage logo](./assets/Birdcage.png)][protection]
```
This is just a suggestion...to make the banner clickable to something other than the image source.

2023-05-03 23:17 UTC, maxrake commented on README.md
> +Trying to run without an exceptions will produce an error:
```suggestion
Trying to run without any exceptions will produce an error:
```

2023-05-03 23:17 UTC, maxrake commented on README.md
> + - macOS via `sandbox_init()` (aka Seatbelt).
```suggestion
 - macOS via `sandbox_init()` (aka Seatbelt)
```

2023-05-04 21:30 UTC, maxrake approved these changes
LGTM

2023-05-04 21:33 UTC, merged